branches:
  only: master
language: python
python: "2.7"
install: pip install Sphinx
script: echo "Scipping build..."
before_deploy: wget https://raw.githubusercontent.com/romanvm/travis_scripts/master/publish_docs.py
deploy:
  provider: script
  script: python publish_docs.py
  skip_cleanup: true
notifications:
  email: false
